### ISSUE TITLE
How to use this ?

### ISSUE THREAD

**Issue by iulicafarafrica** [kyle-rader/breacher#1]
hello, im noob in compiling, but i figured how. Now what ? how to use the .exe ?

**Comment by kyle-rader** [comment]
This is a work in progress and the exe is not yet useful. Note that once
finished, one will have to type out the full matrix, which can take longer
than simply solving  it manually ;)

**Comment by kyle-rader** [comment]
@iulicafarafrica I've completed the first version of this. It's now fully functional. Lots of room for improvement on visually displaying the solution but it can now be used to solve puzzles :). See the [readme](https://github.com/kyle-rader/breacher) for instructions and feel free to leave suggestions!
